image: golang:1.13-stretch

stages:
  - test
  - build

before_script:
  - go list -e $(go list -f '{{.Path}}' -m all 2>/dev/null)
  - which ssh || ( apt-get update -y && apt-get install openssh-client rsync -y )
  - mkdir -p ~/.ssh
  - echo "$ADSDEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
  stage: test
  script:
    - go test -timeout 300s ./...

build:
  stage: build
  script:
    - git remote show origin
    - git remote set-url --push origin git@github.com:webediads/adsgolib.git
    - git remote show origin
    - git rm README.md    
    - git config --global user.email "adserver@webedia-group.com"
    - git config --global user.name "adsdeploy from gitlab"
    - git commit -am "push from gitlab"
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
   
